### PR TITLE
changes in styling

### PR DESCRIPTION
**Pull request by HARI-124**

### CODE REVIEW

**Comment by Aarjav-Jain** [comment]
image

The connect us block is creating problems in responsiveness

**Comment by Aarjav-Jain** [comment]
image
these club icons are very large and does not look good
i think 300px should be good max-width for the ssc logo and 150px for the club logos
also try to maintain the original aspect ratios of the images especially for social projects club logo

**Comment by Aarjav-Jain** [comment]
image
centering of the logos is also distorted

**Comment by Aarjav-Jain** [comment]
image
keep the original size of the social media logos they were looking good

**Comment by manu-shukla** [comment]
Looks fine from my side

**Comment by Aarjav-Jain** [comment]
> image
> 
> The connect us block is creating problems in responsiveness

**Comment by manu-shukla** [comment]
@Aarjav-Jain  Can be merged. Looks good to me

**Comment by Aarjav-Jain** [comment]
@manu-shukla not yet he is working on making a new component for connect us

**Comment by HARI-124** [comment]
added new connect component

**Pull request merged**
